only_rules:
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - comment_spacing
  - control_statement
  - duplicate_imports
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - no_space_in_method_call
  - opening_brace
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_type_annotation
  - redundant_void_return
  - sorted_imports
  